### ISSUE TITLE
"month" placeholder text cropped

### ISSUE THREAD

**Issue by hugovk** [City-of-Helsinki/kukkuu-ui#141]
* macOS Mojave
* Chrome 79

The box needs to be a bit wider to prevent cropping the "month" placeholder text: 

![image](https://user-images.githubusercontent.com/1324225/73539226-91e6d100-4435-11ea-9dd8-2bdcc127e88f.png)

**Comment by hugovk** [comment]
Similarly the date in Swedish:

![image](https://user-images.githubusercontent.com/1324225/73540471-b4c6b480-4438-11ea-99d9-7d61a11d2f46.png)

**Comment by badrange** [comment]
Thank you for reporting this! I added it to our project Jira: https://helsinkisolutionoffice.atlassian.net/browse/KK-251

**Comment by badrange** [comment]
Good news, this was fixed in an unrelated pull request a while ago. Thank you for reporting!
