### ISSUE TITLE
Consider min and max for year field

### ISSUE THREAD

**Issue by hugovk** [City-of-Helsinki/kukkuu-ui#142]
* macOS Mojave
* Chrome 79

The date and month fields have min and max values, consider adding some to the year as well:

![image](https://user-images.githubusercontent.com/1324225/73539324-cfe3f500-4435-11ea-88b9-332e164b968c.png)

**Comment by badrange** [comment]
Great observation! I wish we had dealt with this earlier: 

We just had a few user tests, and several users started clicking the arrow buttons, and the year started from 0, and they were wondering if they had to click it 2020 times more. Ouch! 

We solve it now by adding a min value and hiding those arrows.

**Comment by hugovk** [comment]
It's great to have user tests!
