### ISSUE TITLE
Login page in Finnish when using English or Swedish site

### ISSUE THREAD

**Issue by hugovk** [City-of-Helsinki/kukkuu-ui#146]
1. Start from English (or Swedish) site
2. Enter details and click "Register"

![image](https://user-images.githubusercontent.com/1324225/73540410-85b04300-4438-11ea-81fa-3f0752ce701c.png)

Expected result: login page is English (or Swedish)

Actual result: login page is Finnish

![image](https://user-images.githubusercontent.com/1324225/73540440-9c569a00-4438-11ea-8c8b-da9a871c5193.png)

**Comment by badrange** [comment]
Thank you for this, good spot! I added it to our Jira: https://helsinkisolutionoffice.atlassian.net/browse/KK-250

**Comment by badrange** [comment]
We have now merged a fix for this. It will be updated in our next release scheduled in a few weeks. 

How come it takes so long you ask? A proper CD pipeline is in the works I answer!

**Comment by hugovk** [comment]
Good news on both counts!
