### ISSUE TITLE
Use Helsingfors logos in Swedish

### ISSUE THREAD

**Issue by hugovk** [City-of-Helsinki/kukkuu-ui#147]
When on the Swedish site, the City of Helsinki logo should be the Swedish "Helsingfors" logo.

![image](https://user-images.githubusercontent.com/1324225/73540643-243ca400-4439-11ea-9470-4f3adeb4d85b.png)

![image](https://user-images.githubusercontent.com/1324225/73540648-27d02b00-4439-11ea-909b-fdf8fb81af12.png)

---

Compare https://www.myhelsinki.fi/sv:

![image](https://user-images.githubusercontent.com/1324225/73540684-433b3600-4439-11ea-8e8f-e7b5313b5095.png)

![image](https://user-images.githubusercontent.com/1324225/73540693-49311700-4439-11ea-8082-5f5661280c7a.png)

**Comment by Nizar-Rahme** [comment]
The logo from Helsinki Design System would do the trick
